### ISSUE TITLE
Component for read more paragraph

### ISSUE THREAD

**Issue by ncktrnr** [IIED-org/pubs#212]
Box with read more / read less function

There is a paragraph type already in use called Info box, with a single basic text field. We currently use Readmore.js (https://www.drupal.org/project/readmorejs) to create these, but would be better if the functionality could be included within a twig template.

Example below, currently used for aside elements like info boxes and or transcripts. 

https://www.iied.org/what-makes-sustainable-diet-who-decides-make-change-happen-podcast-episode-5
https://www.iied.org/biodiversity-loss-more-environmental-emergency
https://www.iied.org/urbanising-world
https://www.iied.org/biodiversity-loss-more-environmental-emergency

Exact behaviour may depend on what’s easiest to implement. I think the current version sets a default fixed height, but the show/hide button could otherwise appear after the first paragraph. I also spotted a line-clamp plugin for Tailwind that might be useful for truncating text 
https://github.com/tailwindlabs/tailwindcss-line-clamp

**Comment by ncktrnr** [comment]
See below for suggested HTML and Tailwind classes. The info icon is optional. 

`<div class="p-4 mb-8 prose border border-gray-300 rounded-xl">
        <h3 class="flex items-start">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="flex-shrink-0 w-8 h-8 mr-2 text-iiedblue-500"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            stroke-width="2"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
            />
          </svg>
          Where does Africa fit in the Belt and Road Initiative?
        </h3>
        <p>
          Where does Africa fit in the Belt and Road Initiative? A trillion
          dollars, more than 70% of the world’s population, and huge ambition
          are woven together in China’s Belt and Road Initiative (BRI). Called
          ‘one belt, one road’ in Chinese, it’s a revival of China’s ancient
          transcontinental land and sea silk roads. But there is little
          nostalgia in BRI.
        </p>
        <button
          class="flex items-center px-4 py-2 text-gray-900 transition rounded-full bg-iiedblue-500 -mb-9 hover:bg-iiedblue-600"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="w-6 h-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            stroke-width="2"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 6v6m0 0v6m0-6h6m-6 0H6"
            />
          </svg>
          Show
        </button>
      </div>
      
      <button
        class="flex items-center px-4 py-2 text-gray-900 transition rounded-full bg-iiedblue-500 -mb-9 hover:bg-iiedblue-600"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="w-6 h-6 shrink-0"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          stroke-width="2"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M18 12H6" />
        </svg>
        Hide
      </button>`

**Comment by finnlewis** [comment]
Hey @ncktrnr 

I can't find any examples of Alpine JS and Tailwind doing the same thing as https://jedfoster.com/Readmore.js/

The closest thing I've found is https://codepen.io/KevinBatdorf/pen/NWxPBdQ

I had a play with that to see if I could change the behaviour towards showing some and then all of the content, but didn't get very far. 

Would you like me to use https://jedfoster.com/Readmore.js/ in a paragraph theme template to replicate the current behaviour, or can you see a better way with Alpine? 

Happy to talk if you've got time

**Comment by ncktrnr** [comment]
Just looking at this again the Alphine JS x-show provides a way to show/hide elements, but looks like it would need quite a bit of formatting work to appear in exactly the same way. Readmore.js may well be better suited. The module we used previously is D7 only, but I came across another https://www.drupal.org/project/readmore_js. Also looks like it might integrate better with paragraphs.

**Comment by finnlewis** [comment]
Seems to work! 

![image](https://user-images.githubusercontent.com/326588/184647065-3d01d085-6003-48c6-a047-75e48e14d736.png)


![image](https://user-images.githubusercontent.com/326588/184647104-42204761-b18b-4cfc-89a7-9c5937374eb8.png)


See https://github.com/IIED-org/IIED-main/pull/373/files

**Comment by mattjobob** [comment]
This looks good. Styling looks good as well.

However, clicking on the 'show' doesn't seem to work - nothing happens? https://iied-main-stage.ac.iied.org/test-blog @ncktrnr

**Comment by ncktrnr** [comment]
This should be working, but there is an issue with the hide button scrolling to top of page rather than stopping at the top of the box.

**Comment by mattjobob** [comment]
This still isn't working for me when I test on this page: https://iied-main-stage.ac.iied.org/test-blog although I've seen it working elsewhere.

Re the issue with the hide button returning users to the top of the page, will this be fixed, or left to resolve later?
